"""
Report writer — mirrors ReportWriter.cs.
Generates the same 4 files per job: report.json, report.md, {TICKER}.md, {TICKER}_agent_traces.md
"""

from __future__ import annotations
import json
import os
from datetime import datetime
from models import (
    PortfolioReport, StockReport, InvestmentAction, RiskLevel, AgentTrace,
)


EMOJI = {
    InvestmentAction.StrongBuy:  "🟢",
    InvestmentAction.Buy:        "🔵",
    InvestmentAction.Hold:       "🟡",
    InvestmentAction.Sell:       "🟠",
    InvestmentAction.StrongSell: "🔴",
}
RISK_EMOJI = {
    RiskLevel.Low: "🟢", RiskLevel.Medium: "🟡",
    RiskLevel.High: "🟠", RiskLevel.VeryHigh: "🔴",
}


class ReportWriter:
    def __init__(self, output_dir: str = "./reports"):
        self.output_dir = output_dir

    async def write_report(self, job_id: str, report: PortfolioReport) -> str:
        directory = os.path.join(self.output_dir, job_id)
        os.makedirs(directory, exist_ok=True)

        # report.json
        with open(os.path.join(directory, "report.json"), "w", encoding="utf-8") as f:
            f.write(report.model_dump_json(indent=2))

        # report.md
        with open(os.path.join(directory, "report.md"), "w", encoding="utf-8") as f:
            f.write(_build_portfolio_md(report))

        # Individual ticker files
        for sr in report.stock_reports:
            with open(os.path.join(directory, f"{sr.ticker}.md"), "w", encoding="utf-8") as f:
                f.write(f"# {sr.ticker} — {sr.recommendation.company_name}\n")
                f.write(f"*{sr.generated_at.strftime('%Y-%m-%d %H:%M')} UTC*\n\n")
                f.write(_build_ticker_section(sr))

            with open(os.path.join(directory, f"{sr.ticker}_agent_traces.md"), "w", encoding="utf-8") as f:
                f.write(_build_trace_md(sr))

        return directory


# ─────────────────────────────────────────────────────────────────────────────

def _build_portfolio_md(report: PortfolioReport) -> str:
    lines = [
        "# 📊 Multi-Agent Financial Investment Analysis",
        f"**Job ID:** `{report.job_id}` | **Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M')} UTC",
        "",
        "---",
        "## 🎯 Executive Summary",
        f"> {report.executive_summary}",
        "",
        "## 📈 Portfolio Overview",
        "",
        "| Ticker | Action | Confidence | Price | Target | Upside | Risk | Fund. | Sentiment |",
        "|--------|--------|-----------|-------|--------|--------|------|-------|-----------|",
    ]

    for sr in sorted(report.stock_reports, key=lambda r: r.recommendation.confidence, reverse=True):
        r  = sr.recommendation
        em = EMOJI.get(r.action, "⚪")
        re_ = RISK_EMOJI.get(r.risk_level, "⚪")
        price   = f"${r.current_price:.2f}" if r.current_price else "N/A"
        target  = f"${r.price_target:.2f}" if r.price_target else "N/A"
        upside  = f"{r.upside_percent:+.1f}%" if r.upside_percent is not None else "N/A"
        lines.append(
            f"| **{r.ticker}** | {em} {r.action} | {r.confidence:.0f}% | "
            f"{price} | {target} | {upside} | "
            f"{re_} {r.risk_level} | {r.fundamental.score:.0f}/100 ({r.fundamental.grade}) | {r.sentiment.overall} |"
        )

    lines += ["", "---", ""]
    for sr in report.stock_reports:
        lines.append(_build_ticker_section(sr))
        lines.append("---")

    lines += [
        "",
        "> *Generated by Multi-Agent Agentic Financial Advisor — 5 autonomous CrewAI agents*",
        "> **Not financial advice.**",
    ]
    return "\n".join(lines)


def _build_ticker_section(sr: StockReport) -> str:
    r    = sr.recommendation
    em   = EMOJI.get(r.action, "⚪")
    re_  = RISK_EMOJI.get(r.risk_level, "⚪")
    price  = f"${r.current_price:.2f}" if r.current_price else "N/A"
    target = f"${r.price_target:.2f}" if r.price_target else "N/A"
    upside = f"{r.upside_percent:+.1f}%" if r.upside_percent is not None else "N/A"

    lines = [
        f"### {em} {r.ticker} — {r.action} | {r.confidence:.0f}% Confidence",
        f"**Price:** {price} → **Target:** {target} ({upside}) | **Horizon:** {r.time_horizon} | **Risk:** {re_} {r.risk_level}",
        "",
        "#### 🏛️ CIO Investment Memo",
        f"> {(r.cio_summary or '')[:500]}",
        "",
        "#### 🤖 Agent Score Cards",
        "| Agent | Result | Steps |",
        "|-------|--------|-------|",
    ]

    dc_steps = next((t.total_steps for t in sr.all_traces if t.agent_name == "DataCollectionAgent"), 0)
    lines += [
        f"| 1️⃣ DataCollection | Collected: {len(sr.raw_data.news)} news, {len(sr.raw_data.analyst_ratings)} ratings | {dc_steps} |",
        f"| 2️⃣ Fundamental | Score: {r.fundamental.score:.0f}/100 Grade {r.fundamental.grade} | {r.fundamental.trace.total_steps} |",
        f"| 3️⃣ Sentiment | {r.sentiment.overall} ({r.sentiment.score:+.2f}) | {r.sentiment.trace.total_steps} |",
        f"| 4️⃣ Risk | {r.risk.level} ({r.risk.score:.0f}/100) | {r.risk.trace.total_steps} |",
        f"| 5️⃣ CIO | {r.action} @ {r.confidence:.0f}% confidence | {r.cio_trace.total_steps} |",
        "",
        "#### 🔬 Fundamental Analysis",
        f"**Score:** {r.fundamental.score:.0f}/100 | **Grade:** {r.fundamental.grade}",
    ]

    if r.fundamental.strengths:
        lines.append("**Strengths:**")
        for s in r.fundamental.strengths:
            lines.append(f"- ✅ {s}")
    if r.fundamental.weaknesses:
        lines.append("**Weaknesses:**")
        for w in r.fundamental.weaknesses:
            lines.append(f"- ❌ {w}")

    lines += [
        "",
        "#### 📰 Sentiment Analysis",
        f"**Overall:** {r.sentiment.overall} | **Score:** {r.sentiment.score:+.2f} | "
        f"{r.sentiment.bullish_percent:.0f}% Bull / {r.sentiment.neutral_percent:.0f}% Neutral / {r.sentiment.bearish_percent:.0f}% Bear",
        "",
        "#### ⚠️ Risk Analysis",
        f"**Level:** {r.risk.level} ({r.risk.score:.0f}/100)",
    ]
    for rf in r.risk.risk_factors[:4]:
        lines.append(f"- 🔴 {rf}")

    lines.append("")
    if r.key_catalysts:
        lines.append("**Key Catalysts:**")
        for c in r.key_catalysts:
            lines.append(f"- 🚀 {c}")
    if r.key_risks:
        lines.append("**Key Risks:**")
        for kr in r.key_risks:
            lines.append(f"- ⚡ {kr}")

    m = sr.raw_data.metrics
    lines += [
        "",
        "#### 💹 Key Metrics",
        f"P/E: {m.pe_ratio or 'N/A'} | P/B: {m.pb_ratio or 'N/A'} | Beta: {m.beta or 'N/A'} | "
        f"D/E: {m.debt_to_equity or 'N/A'} | FCF: {(m.free_cash_flow or 0) / 1e9:.1f}B",
        f"52W: ${m.fifty_two_week_low or 'N/A'} – ${m.fifty_two_week_high or 'N/A'} | Sector: {m.sector or 'N/A'}",
        "",
    ]
    return "\n".join(lines)


def _build_trace_md(sr: StockReport) -> str:
    lines = [
        f"# 🧠 Agent Reasoning Traces — {sr.ticker}",
        "*This file shows exactly how each AI agent reasoned and which tools it called.*",
        "",
    ]
    for trace in sr.all_traces:
        goal_preview = (trace.goal or "")[:200]
        lines += [
            "---",
            f"## {trace.agent_name}",
            f"**Goal:** {goal_preview}",
            f"**Steps:** {trace.total_steps} | **Succeeded:** {trace.succeeded}",
            "",
        ]
        if trace.steps:
            for step in trace.steps:
                lines.append(f"### Step {step.step_number}")
                if step.thought:
                    lines.append(f"**💭 Thought:** {step.thought}")
                if step.is_final:
                    fa = (step.final_answer or "")[:400]
                    lines.append(f"**✅ FINAL ANSWER:** {fa}")
                else:
                    if step.action:
                        ai = (step.action_input or "")[:150]
                        lines.append(f"**🔧 Action:** `{step.action}` | **Input:** `{ai}`")
                    if step.observation:
                        obs = step.observation[:300]
                        lines.append(f"**👁️ Observation:** {obs}...")
                lines.append("")
        else:
            # CrewAI doesn't expose individual steps the same way — show the final output
            fa = (trace.final_answer or "")[:600]
            lines += [f"**Output:**\n{fa}", ""]

    return "\n".join(lines)
